remote_theme: eecs485staff/primer-spec
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-default-layout
  - jemoji
kramdown:
  input: GFM
readme_index:
  remove_originals: true
  with_frontmatter: true

title: Jekyll Theme Primer Spec
description: Primer Spec is a Jekyll theme for GitHub Pages

primerSpec:
  sitemap:
    label: Docs & Demos
    # Setting the label to an empty string removes the label from the sitemap.
    # label: ''
    externalLinks:
      - title: Wikipedia
        url: https://www.wikipedia.org/
      - title: 'Google'
        url: https://google.com/
      - title: 'EECS 485'
        url: https://eecs485.org

# defaultCodeblockVariant: no-line-numbers

sass:
  style: :compressed

exclude:
  - .bundle
  - .githooks
  - .github
  - .vscode
  - node_modules
  - script
  - src_js
  - .eslintrc
  - .prettierignore
  - .prettierrc
  - '*.yml'
  - '*.lock'
  - '*.config.js'
  - '*.code-workspace'
  - '*.ts'
  - '*.gem'
  - '*.gemspec'
  - Gemfile
  - package.json
  - package-lock.json
  - tsconfig.json
  - VERSION
  - vendor
