name: upload-develop-preview

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  schedule:
    # Also run on the first day of each month
    - cron: '0 0 1 * *'

jobs:
  upload-develop-preview:
    name: upload-develop-preview
    runs-on: ubuntu-latest
    steps:
      - name: 📁 Checkout code
        uses: actions/checkout@v2

      - name: ♼ Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: ⬢ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: ⚙️ Install dependencies
        run: |
          ./script/bootstrap

      - name: 🛠 Build CI-site-preview build
        env:
          REPO: ${{ github.repository }}
        run: |
          sed -i "\$ s/\$/ (develop preview build: $(date '+%Y-%m-%d') ($(git rev-parse HEAD)))/" VERSION
          ./script/ci-site-preview-build "https://preview.sesh.rs" "/previews/$REPO/develop-preview"

      # Upload the site to Primer Spec Preview and comment on the PR.
      # The Primer Spec Preview secret is stored as an encrypted repo or
      # organization secret named `PRIMER_SPEC_PREVIEW_SECRET`.
      # Docs: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-organization
      # Docs: https://github.com/seshrs/upload-to-primer-spec-preview
      - name: 🚀 Upload to Primer Spec Preview
        uses: seshrs/upload-to-primer-spec-preview@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIMER_SPEC_PREVIEW_SECRET: ${{ secrets.PRIMER_SPEC_PREVIEW_SECRET }}
          custom_basename: develop-preview
